# Generated by Django 6.0.1 on 2026-01-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalityquiz',
            name='q1_romantic',
        ),
        migrations.RemoveField(
            model_name='personalityquiz',
            name='q2_outgoing',
        ),
        migrations.RemoveField(
            model_name='personalityquiz',
            name='q3_deep_talks',
        ),
        migrations.RemoveField(
            model_name='personalityquiz',
            name='q4_planner',
        ),
        migrations.RemoveField(
            model_name='personalityquiz',
            name='q5_spontaneous',
        ),
        migrations.AddField(
            model_name='personalityquiz',
            name='answers',
            field=models.JSONField(default=list, help_text='Array of 9 answers (1-5 Likert scale). Indices: [0,3,6]→cat0, [1,4,7]→cat1, [2,5,8]→cat2'),
        ),
        migrations.AddField(
            model_name='personalityquiz',
            name='calculated_weights',
            field=models.JSONField(default=list, help_text='Array of 3 weighted averages corresponding to categories'),
        ),
        migrations.AddField(
            model_name='personalityquiz',
            name='category_classification',
            field=models.CharField(blank=True, help_text='The category (category_0, category_1, category_2) that best matches the calculated weights', max_length=20),
        ),
        migrations.AddField(
            model_name='personalityquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
