# Generated by Django 6.0.1 on 2026-01-23 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_personalityquiz_q1_romantic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='user',
        ),
        migrations.CreateModel(
            name='AttractionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=list, help_text='Array of 3 answers (1-5 Likert scale) for attraction preferences')),
                ('preferences', models.JSONField(default=list, help_text='Array of 3 preference values corresponding to categories')),
                ('most_attracted_category', models.CharField(blank=True, help_text="The personality category (color) they're most attracted to", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
